name: example-environment
channels:
  - conda-forge
dependencies:
  - yarn
  - pip:
    - git+https://github.com/pole-surfaces-planetaires/pdssp.git@9ff053d0202f5629e9385564aa27debf291fee0e#egg=pdssp
