name: example-environment
channels:
  - conda-forge
dependencies:
  - yarn
  - pip:
    - git+https://github.com/pole-surfaces-planetaires/pdssp.git@3e53228ee6f13b405108e9441a05b7a9192138c1#egg=pdssp
